src/core/urls.py
from django.contrib import admin
from django.urls import include, path

from track.api import (
    BaseScript,
    TrackAPI,
    EventTrackAPI,
    EventTrackingScript,
    TestApi,
    EventApi,
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing.urls")),
    path("", include("user.urls")),
]

debg = [
    path("silk/", include("silk.urls", namespace="silk")),
    # path("__debug__/", include("debug_toolbar.urls")),
]

api = [
    path(
        "api/script.js",
        BaseScript.as_view(),
        name="basescript",
    ),
    path(
        "api/script.event.js",
        EventTrackingScript.as_view(),
        name="event-tracking-script",
    ),
    path(
        "api/track",
        TrackAPI.as_view(),
        name="trackapi",
    ),
    path(
        "api/event",
        EventTrackAPI.as_view(),
        name="event-track-event",
    ),
    path("api/test", TestApi.as_view()),
    path("api/ne", EventApi.as_view()),
]


urlpatterns += debg
urlpatterns += api

src/user/urls.py
from django.urls import path

from .views import login, logout, register_user

urlpatterns = [
    path("login", login, name="login"),
    path("register", register_user, name="register"),
    path("logout", logout, name="logout"),
]

src/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class User(AbstractUser):
    email = models.EmailField(_("email address"), unique=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

src/user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.core.exceptions import ValidationError

from .models import User


class AdminUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email",)


class AdminUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email",)


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        password = cleaned_data.get("password")
        if email and password:
            try:
                user = User.objects.get(email=email)
                if not user.check_password(password):
                    raise ValidationError("Invalid email or password")
            except User.DoesNotExist:
                raise ValidationError("Invalid email or password")
        return cleaned_data


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["email", "password"]

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and confirm_password and password != confirm_password:
            raise ValidationError("Passwords do not match")

        return cleaned_data

src/user/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.shortcuts import redirect, render, reverse
from django.urls import reverse

from icecream import ic

from .forms import LoginForm, RegisterForm
from .models import User

LOGIN_REDIRECT_URL = settings.LOGIN_REDIRECT_URL or reverse("login")


def login(request):
    form = LoginForm(request.POST or None)

    if request.method == "POST":
        ic(form.is_valid)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")

            try:
                user = User.objects.get(email=email)
                user = authenticate(email=email, password=password)

                if user is not None:
                    auth_login(request, user)
                    messages.success(request, "Logged in successfully")
                    return redirect(settings.LOGIN_REDIRECT_URL)
                else:
                    ic("Invalid")
                    messages.error(request, "Invalid email or password.")

            except User.DoesNotExist:
                ic("User not existws")
                messages.error(request, "Invalid email or password.")
        else:
            messages.error(request=request, message="Invalid email or password.")
            return redirect(reverse("login"))

    context = {"form": form}
    return render(request=request, template_name="login.html", context=context)


def register_user(request):
    form = RegisterForm(request.POST or None)

    if request.method == "GET":
        context = {"form": form}
        return render(request=request, template_name="register.html", context=context)

    if request.method == "POST":
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            username = email.split("@")[0]

            user = User.objects.create_user(
                username=username, email=email, password=password
            )
            user.set_password(password)
            user.save()
            messages.success(request, "User registered successfully")
            return redirect("login")
        else:
            messages.error(
                request, "Registration failed. Please correct the errors below."
            )

    context = {"form": form}
    return render(request, "register.html", context)


def logout(request):
    auth_logout(request)
    return redirect("/")

src/user/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.11.1/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
</head>


<body class="bg-gray-100">
    {% include "components/messages.html" %}
    <div class="flex items-center justify-center min-h-screen">
        <div class="bg-white p-6 rounded-lg shadow-md w-80">
            <h1 class="text-2xl font-bold mb-4 text-center text-gray-900">Login to Jamma</h1>
            

            <form action="" method="post">
                {% csrf_token %}
                <div class="mb-4">
                    <label for="id_email" class="input input-bordered flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-4 h-4 opacity-70">
                            <path d="M2.5 3A1.5 1.5 0 0 0 1 4.5v.793c.026.009.051.02.076.032L7.674 8.51c.206.1.446.1.652 0l6.598-3.185A.755.755 0 0 1 15 5.293V4.5A1.5 1.5 0 0 0 13.5 3h-11Z" />
                            <path d="M15 6.954 8.978 9.86a2.25 2.25 0 0 1-1.956 0L1 6.954V11.5A1.5 1.5 0 0 0 2.5 13h11a1.5 1.5 0 0 0 1.5-1.5V6.954Z" />
                        </svg>
                        <input type="email" name="email" id="id_email" class="grow" placeholder="Email" required />
                    </label>
                </div>

                <div class="mb-4">
                    <label for="id_password" class="input input-bordered flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-4 h-4 opacity-70">
                            <path fill-rule="evenodd" d="M14 6a4 4 0 0 1-4.899 3.899l-1.955 1.955a.5.5 0 0 1-.353.146H5v1.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2.293a.5.5 0 0 1 .146-.353l3.955-3.955A4 4 0 1 1 14 6Zm-4-2a.75.75 0 0 0 0 1.5.5.5 0 0 1 .5.5.75.75 0 0 0 1.5 0 2 2 0 0 0-2-2Z" clip-rule="evenodd" />
                        </svg>
                        <input type="password" name="password" id="id_password" class="grow" placeholder="Password" required />
                    </label>
                </div>
                <div>
                    <button type="submit" class="btn w-full" _="on click remove [@hidden] from #login_loading_spinner">
                    <span class="loading loading-spinner" id="login_loading_spinner" hidden></span>
                    Submit</button>
                </div>

                <div class="mt-4 text-center">
                    <a href="{% url 'register' %}" class="link link-primary">Register Page</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

src/user/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }} | Registration</title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.11.1/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-100">
    <div class="flex items-center justify-center min-h-screen">
        <div class="bg-white p-6 rounded-lg shadow-md w-80">
            <h1 class="text-2xl font-bold mb-4 text-center text-gray-1000">Register Page</h1>

            <form action="" method="post">
                {% csrf_token %}

                <div class="mb-4">
                    <label for="id_email" class="input input-bordered flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-4 h-4 opacity-70">
                            <path d="M2.5 3A1.5 1.5 0 0 0 1 4.5v.793c.026.009.051.02.076.032L7.674 8.51c.206.1.446.1.652 0l6.598-3.185A.755.755 0 0 1 15 5.293V4.5A1.5 1.5 0 0 0 13.5 3h-11Z" />
                            <path d="M15 6.954 8.978 9.86a2.25 2.25 0 0 1-1.956 0L1 6.954V11.5A1.5 1.5 0 0 0 2.5 13h11a1.5 1.5 0 0 0 1.5-1.5V6.954Z" />
                        </svg>
                        <input type="email" name="email" id="id_email" class="grow" placeholder="Email" required />
                    </label>
                </div>

                <div class="mb-4">
                    <label for="id_password" class="input input-bordered flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-4 h-4 opacity-70">
                            <path fill-rule="evenodd" d="M14 6a4 4 0 0 1-4.899 3.899l-1.955 1.955a.5.5 0 0 1-.353.146H5v1.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2.293a.5.5 0 0 1 .146-.353l3.955-3.955A4 4 0 1 1 14 6Zm-4-2a.75.75 0 0 0 0 1.5.5.5 0 0 1 .5.5.75.75 0 0 0 1.5 0 2 2 0 0 0-2-2Z" clip-rule="evenodd" />
                        </svg>
                        <input type="password" name="password" id="id_password" class="grow" placeholder="Password" required />
                    </label>
                </div>

                <div class="mb-4">
                    <label for="id_confirm_password" class="input input-bordered flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-4 h-4 opacity-70">
                            <path fill-rule="evenodd" d="M14 6a4 4 0 0 1-4.899 3.899l-1.955 1.955a.5.5 0 0 1-.353.146H5v1.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2.293a.5.5 0 0 1 .146-.353l3.955-3.955A4 4 0 1 1 14 6Zm-4-2a.75.75 0 0 0 0 1.5.5.5 0 0 1 .5.5.75.75 0 0 0 1.5 0 2 2 0 0 0-2-2Z" clip-rule="evenodd" />
                        </svg>
                        <input type="password" name="confirm_password" id="id_confirm_password" class="grow" placeholder="Confirm Password" required />
                    </label>
                </div>

                <button type="submit" class="btn  w-full">Register</button>

                <div class="mt-4 text-center">
                    <p>Already Registered? 
                        <a href="{% url 'login' %}" class="link link-primary">Login Here</a>
                    </p>
                </div>
            </form>
        </div>
    </div>
</body>
</html>